"""
Single Source of Truth for Feature Extraction.
Used identically during training dataset preprocessing and production API inference.
"""

import math
import re
from typing import Dict, List, Tuple, Any
from urllib.parse import urlparse, parse_qs
import ipaddress

# Known URL shortener services
SHORTENERS = {
    'bit.ly', 'tinyurl.com', 'goo.gl', 't.co', 'ow.ly', 'is.gd', 'buff.ly',
    'adf.ly', 'bitly.com', 'cutt.ly', 'rb.gy', 'shorte.st', 'tiny.cc', 'bc.vc',
    'v.gd', 'qr.ae', 'trib.al', 'soo.gd', 's2r.co', 'clicky.me'
}

# Suspicious keywords frequently observed in phishing URLs
SUSPICIOUS_KEYWORDS = [
    'login', 'verify', 'update', 'secure', 'account', 'banking', 'signin',
    'confirm', 'security', 'wallet', 'service', 'support', 'password',
    'auth', 'ebayisapi', 'paypal', 'appleid', 'recover', 'billing', 'verification',
    'webscr', 'cmd', 'authenticate', 'free', 'bonus', 'alert', 'upgrade'
]

IP_V4_PATTERN = re.compile(r'^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$')

FEATURE_NAMES: List[str] = [
    'url_length',
    'domain_length',
    'path_length',
    'query_length',
    'num_dots',
    'num_hyphens',
    'num_underscores',
    'num_slashes',
    'num_question_marks',
    'num_equal_signs',
    'num_ampersands',
    'num_at_symbols',
    'num_percent_signs',
    'num_digits',
    'digit_ratio',
    'num_letters',
    'letter_ratio',
    'num_special_chars',
    'special_char_ratio',
    'is_https',
    'is_ip_domain',
    'num_subdomains',
    'has_port',
    'num_path_dirs',
    'num_query_params',
    'is_shortened',
    'suspicious_keyword_count',
    'char_continuation_rate',
    'entropy',
    'tld_length',
    'has_punycode',
    'consecutive_hyphens',
    'has_obfuscation'
]


def normalize_url(url: str) -> str:
    """
    Normalizes a URL string:
    - Strips leading/trailing whitespace
    - Ensures a default scheme (http://) if missing for parsing
    - Handles case normalization for domain while preserving path
    """
    if not url:
        return ""
    url = url.strip()
    return url


def validate_url(url: str) -> Tuple[bool, str]:
    """
    Validates a URL before processing.
    Returns (is_valid, error_message).
    """
    if not url or not url.strip():
        return False, "URL cannot be empty."
    
    cleaned = url.strip()
    if len(cleaned) > 2048:
        return False, "URL exceeds maximum supported length (2048 characters)."
    
    # Check for basic invalid characters or control characters
    if any(ord(c) < 32 or ord(c) == 127 for c in cleaned):
        return False, "URL contains invalid control characters."

    # Parse test
    url_to_parse = cleaned if cleaned.startswith(('http://', 'https://')) else 'http://' + cleaned
    try:
        parsed = urlparse(url_to_parse)
        if not parsed.netloc and not parsed.path:
            return False, "Malformed URL: missing domain and path."
    except Exception as e:
        return False, f"Malformed URL parsing error: {str(e)}"

    return True, ""


def calc_entropy(text: str) -> float:
    """
    Calculates Shannon entropy of character distribution in text.
    High entropy indicates random strings (often generated by DGAs).
    """
    if not text:
        return 0.0
    length = len(text)
    prob_dist = [text.count(c) / length for c in set(text)]
    return -sum(p * math.log2(p) for p in prob_dist)


def char_continuation_rate(text: str) -> float:
    """
    Calculates continuation rate: length of longest sequence of consecutive
    characters of the same category (Letter, Digit, Special) divided by total length.
    """
    if not text:
        return 0.0
    max_cont = 1
    curr_cont = 1
    prev_type = None
    for c in text:
        curr_type = 'L' if c.isalpha() else ('D' if c.isdigit() else 'S')
        if curr_type == prev_type:
            curr_cont += 1
            if curr_cont > max_cont:
                max_cont = curr_cont
        else:
            curr_cont = 1
            prev_type = curr_type
    return max_cont / len(text)


def extract_features(url: str) -> Dict[str, Any]:
    """
    Extracts 33 deterministic URL-derived features from a given URL string.
    Single source of truth for both model training and live API inference.
    """
    url_clean = normalize_url(url)
    if not url_clean.startswith(('http://', 'https://')):
        url_for_parsing = 'http://' + url_clean
    else:
        url_for_parsing = url_clean

    try:
        parsed = urlparse(url_for_parsing)
    except Exception:
        # Fallback for heavily malformed strings
        parsed = urlparse('http://invalid.url')

    # Domain / Netloc extraction
    netloc = parsed.netloc or ""
    # Strip port if present for domain analysis
    domain = netloc.split(':')[0].lower() if netloc else ""
    path = parsed.path or ""
    query = parsed.query or ""

    # IP address check
    is_ip = 0
    if domain:
        try:
            ipaddress.ip_address(domain)
            is_ip = 1
        except ValueError:
            if IP_V4_PATTERN.match(domain):
                is_ip = 1

    # Subdomains and TLD
    domain_parts = domain.split('.') if domain else []
    if is_ip or not domain_parts:
        tld = ''
        tld_length = 0
        num_subdomains = 0
    else:
        tld = domain_parts[-1] if len(domain_parts) > 1 else ''
        tld_length = len(tld)
        # Filter 'www' and TLD to count true subdomains
        subparts = [p for p in domain_parts if p != 'www']
        num_subdomains = max(0, len(subparts) - 2)

    url_len = len(url_clean)
    num_digits = sum(c.isdigit() for c in url_clean)
    num_letters = sum(c.isalpha() for c in url_clean)
    num_special = url_len - (num_digits + num_letters)

    # Keywords count
    url_lower = url_clean.lower()
    keyword_count = sum(1 for kw in SUSPICIOUS_KEYWORDS if kw in url_lower)

    # Query params
    try:
        params = parse_qs(query)
        num_query_params = len(params)
    except Exception:
        num_query_params = 0

    path_dirs = [d for d in path.split('/') if d]

    features = {
        'url_length': url_len,
        'domain_length': len(domain),
        'path_length': len(path),
        'query_length': len(query),
        'num_dots': url_clean.count('.'),
        'num_hyphens': url_clean.count('-'),
        'num_underscores': url_clean.count('_'),
        'num_slashes': url_clean.count('/'),
        'num_question_marks': url_clean.count('?'),
        'num_equal_signs': url_clean.count('='),
        'num_ampersands': url_clean.count('&'),
        'num_at_symbols': url_clean.count('@'),
        'num_percent_signs': url_clean.count('%'),
        'num_digits': num_digits,
        'digit_ratio': (num_digits / url_len) if url_len > 0 else 0.0,
        'num_letters': num_letters,
        'letter_ratio': (num_letters / url_len) if url_len > 0 else 0.0,
        'num_special_chars': num_special,
        'special_char_ratio': (num_special / url_len) if url_len > 0 else 0.0,
        'is_https': 1 if url_clean.lower().startswith('https://') else 0,
        'is_ip_domain': is_ip,
        'num_subdomains': num_subdomains,
        'has_port': 1 if parsed.port is not None else 0,
        'num_path_dirs': len(path_dirs),
        'num_query_params': num_query_params,
        'is_shortened': 1 if domain in SHORTENERS else 0,
        'suspicious_keyword_count': keyword_count,
        'char_continuation_rate': char_continuation_rate(url_clean),
        'entropy': calc_entropy(url_clean),
        'tld_length': tld_length,
        'has_punycode': 1 if 'xn--' in domain else 0,
        'consecutive_hyphens': 1 if '--' in url_clean else 0,
        'has_obfuscation': 1 if '%' in url_clean else 0
    }

    return features
